import "~/styles/globals.css";
import "@mantine/core/styles.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { MantineProvider } from "@mantine/core";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital@0;1&family=Roboto:wght@300&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <MantineProvider
            theme={{
              fontFamily: "Lato sans-serif",
            }}
            defaultColorScheme="dark"
          >
            {children}
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
